# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Mon Mar 18 15:11:41 PDT 2013
#
#/ usage: ircbot:connect  --channel <> [ --server <irc.freenode.net>] [ --nick <irclog>]  --log <> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --channel) rerun_option_check $# $1; CHANNEL=$2 ; shift ;;
            --server) rerun_option_check $# $1; SERVER=$2 ; shift ;;
            --nick) rerun_option_check $# $1; NICK=$2 ; shift ;;
            --log) rerun_option_check $# $1; LOG=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$SERVER" ] && SERVER="$(rerun_property_get $RERUN_MODULE_DIR/options/server DEFAULT)"
    [ -z "$NICK" ] && NICK="$(rerun_property_get $RERUN_MODULE_DIR/options/nick DEFAULT)"
    # Check required options are set
    [ -z "$CHANNEL" ] && { echo >&2 "missing required option: --channel" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
CHANNEL=
SERVER=
NICK=
LOG=


