# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Mon Mar 18 11:09:51 PDT 2013
#
#/ usage: ircbot:digest [ --format <ghpost>] [ --server <irc.freenode.net>]  --channel <> [ --dir <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --format) rerun_option_check $# $1; FORMAT=$2 ; shift ;;
            --server) rerun_option_check $# $1; SERVER=$2 ; shift ;;
            --channel) rerun_option_check $# $1; CHANNEL=$2 ; shift ;;
            --dir) rerun_option_check $# $1; DIR=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$FORMAT" ] && FORMAT="$(rerun_property_get $RERUN_MODULE_DIR/options/format DEFAULT)"
    [ -z "$SERVER" ] && SERVER="$(rerun_property_get $RERUN_MODULE_DIR/options/server DEFAULT)"
    # Check required options are set
    [ -z "$CHANNEL" ] && { echo >&2 "missing required option: --channel" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
FORMAT=
SERVER=
CHANNEL=
DIR=


